name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    env:
      MY_ENV_VAR: "Hello, World!"
      HELLO: "Hello, World!"    
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJSON(env)}}"
      - run: echo "${{toJSON(vars)}}"
      - run: echo "${{toJSON(secrets)}}"
      - run: echo "${{toJSON(runner)}}"
